### POST users
POST http://localhost:3333/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGFsbGVzIiwiZW1haWwiOiJ0YWxsZXNAZXhlbXBsZS5jb20iLCJpYXQiOjE3MzE5NzA2NTQsImV4cCI6MTczNDU2MjY1NCwic3ViIjoiNTFkM2U2NTItYWZlMy00ZGIxLWIwM2MtYzk1Mzg2NmExOGY2In0.HYeJsmDcndeQDggK0CHZjemda1ab_9IrCIUbg4ZWNXQ

{
   "name":"Talles",
   "email":"teste5@exemple.com",
   "password":"123456"
}


### GET me
GET http://localhost:3333/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGFsbGVzIiwiZW1haWwiOiJ0YWxsZXNAZXhlbXBsZS5jb20iLCJpYXQiOjE3MzExMTM4OTAsImV4cCI6MTczMzcwNTg5MCwic3ViIjoiNTFkM2U2NTItYWZlMy00ZGIxLWIwM2MtYzk1Mzg2NmExOGY2In0.a-FaUSgIgZwMahT6fRKh7J_Wkwjnx-zGPuZ3-xfthZY
